// Mock data for testing without Supabase/LIFF

export const IS_MOCK_MODE = !process.env.NEXT_PUBLIC_SUPABASE_URL || !process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;

export const mockShopSettings = {
  id: 'mock-shop-1',
  shop_name: 'ร้านอาหารทดสอบ',
  shop_description: 'ร้านอาหารอร่อยสำหรับทดสอบระบบ',
  logo_url: null,
  cover_image_url: null,
  phone: '081-234-5678',
  address: '123 ถนนสุขุมวิท กรุงเทพฯ 10110',
  opening_hours: {
    mon: { open: '09:00', close: '21:00' },
    tue: { open: '09:00', close: '21:00' },
    wed: { open: '09:00', close: '21:00' },
    thu: { open: '09:00', close: '21:00' },
    fri: { open: '09:00', close: '22:00' },
    sat: { open: '10:00', close: '22:00' },
    sun: { open: '10:00', close: '20:00' },
  },
  is_open: true,
  min_pickup_time: 15,
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
};

export const mockCategories = [
  {
    id: 'cat-1',
    name: 'อาหารจานเดียว',
    description: 'อาหารจานเดียวหลากหลาย',
    sort_order: 1,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'cat-2',
    name: 'ก๋วยเตี๋ยว',
    description: 'ก๋วยเตี๋ยวน้ำใสและต้มยำ',
    sort_order: 2,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'cat-3',
    name: 'เครื่องดื่ม',
    description: 'เครื่องดื่มเย็นและร้อน',
    sort_order: 3,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

// Category Options - ตัวเลือกประจำหมวดหมู่
export const mockCategoryOptions = [
  {
    id: 'opt-1',
    category_id: 'cat-3', // เครื่องดื่ม
    name: 'ความหวาน',
    choices: [
      { label: 'ปกติ', price: 0 },
      { label: 'หวานน้อย', price: 0 },
      { label: 'หวานมาก', price: 0 },
      { label: 'ไม่หวาน', price: 0 },
    ],
    is_required: true,
    allow_multiple: false,
    sort_order: 1,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'opt-2',
    category_id: 'cat-3', // เครื่องดื่ม
    name: 'ประเภท',
    choices: [
      { label: 'ร้อน', price: 0 },
      { label: 'เย็น', price: 5 },
      { label: 'ปั่น', price: 10 },
    ],
    is_required: true,
    allow_multiple: false,
    sort_order: 2,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'opt-3',
    category_id: 'cat-1', // อาหารจานเดียว
    name: 'ความเผ็ด',
    choices: [
      { label: 'ไม่เผ็ด', price: 0 },
      { label: 'เผ็ดน้อย', price: 0 },
      { label: 'เผ็ดกลาง', price: 0 },
      { label: 'เผ็ดมาก', price: 0 },
    ],
    is_required: false,
    allow_multiple: false,
    sort_order: 1,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'opt-4',
    category_id: 'cat-1', // อาหารจานเดียว
    name: 'ท็อปปิ้ง',
    choices: [
      { label: 'ไข่ดาว', price: 10 },
      { label: 'ไข่เจียว', price: 10 },
      { label: 'หมูกรอบ', price: 15 },
    ],
    is_required: false,
    allow_multiple: true,
    sort_order: 2,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const mockMenuItems = [
  {
    id: 'item-1',
    category_id: 'cat-1',
    name: 'ข้าวผัดหมู',
    description: 'ข้าวผัดหมูสูตรต้นตำรับ ใส่ไข่และผักสด',
    price: 50,
    is_available: true,
    is_recommended: true,
    preparation_time: 10,
    sort_order: 1,
    options: [
      { name: 'ความเผ็ด', choices: [{ label: 'ไม่เผ็ด', price: 0 }, { label: 'เผ็ดน้อย', price: 0 }, { label: 'เผ็ดมาก', price: 0 }] },
      { name: 'ไข่', choices: [{ label: 'ไข่ดาว', price: 10 }, { label: 'ไข่เจียว', price: 10 }] },
    ],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'item-2',
    category_id: 'cat-1',
    name: 'ข้าวกะเพราหมูสับ',
    description: 'ผัดกะเพราหมูสับ รสจัดจ้าน',
    price: 55,
    is_available: true,
    is_recommended: true,
    preparation_time: 8,
    sort_order: 2,
    options: [
      { name: 'ความเผ็ด', choices: [{ label: 'ไม่เผ็ด', price: 0 }, { label: 'เผ็ดน้อย', price: 0 }, { label: 'เผ็ดมาก', price: 0 }] },
    ],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'item-3',
    category_id: 'cat-1',
    name: 'ข้าวไข่เจียว',
    description: 'ไข่เจียวฟูกรอบ',
    price: 40,
    is_available: true,
    is_recommended: false,
    preparation_time: 5,
    sort_order: 3,
    options: [],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'item-4',
    category_id: 'cat-2',
    name: 'ก๋วยเตี๋ยวหมูน้ำใส',
    description: 'เส้นหมี่กับหมูชิ้นและหมูบด',
    price: 45,
    is_available: true,
    is_recommended: false,
    preparation_time: 7,
    sort_order: 1,
    options: [
      { name: 'เส้น', choices: [{ label: 'เส้นเล็ก', price: 0 }, { label: 'เส้นใหญ่', price: 0 }, { label: 'บะหมี่', price: 0 }] },
    ],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'item-5',
    category_id: 'cat-2',
    name: 'ต้มยำก๋วยเตี๋ยว',
    description: 'ต้มยำรสเด็ด เผ็ดร้อน',
    price: 55,
    is_available: true,
    is_recommended: true,
    preparation_time: 10,
    sort_order: 2,
    options: [
      { name: 'เส้น', choices: [{ label: 'เส้นเล็ก', price: 0 }, { label: 'เส้นใหญ่', price: 0 }, { label: 'มาม่า', price: 0 }] },
    ],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'item-6',
    category_id: 'cat-3',
    name: 'ชาเย็น',
    description: 'ชาไทยใส่นมหวานเย็นชื่นใจ',
    price: 25,
    is_available: true,
    is_recommended: false,
    preparation_time: 3,
    sort_order: 1,
    options: [
      { name: 'ความหวาน', choices: [{ label: 'หวานปกติ', price: 0 }, { label: 'หวานน้อย', price: 0 }, { label: 'ไม่หวาน', price: 0 }] },
    ],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'item-7',
    category_id: 'cat-3',
    name: 'กาแฟเย็น',
    description: 'กาแฟโบราณใส่นม',
    price: 30,
    is_available: true,
    is_recommended: false,
    preparation_time: 3,
    sort_order: 2,
    options: [],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'item-8',
    category_id: 'cat-3',
    name: 'น้ำมะนาว',
    description: 'น้ำมะนาวสดคั้น',
    price: 20,
    is_available: true,
    is_recommended: false,
    preparation_time: 2,
    sort_order: 3,
    options: [],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

// Generate mock orders with different statuses
const now = new Date();
export const mockOrders = [
  {
    id: 'order-1',
    order_number: 'ORD-001',
    line_user_id: 'mock-user-123',
    customer_name: 'สมชาย ใจดี',
    customer_phone: '081-111-1111',
    status: 'pending' as const,
    total_amount: 105,
    pickup_time: new Date(now.getTime() + 30 * 60000).toISOString(),
    notes: null,
    cancelled_reason: null,
    created_at: new Date(now.getTime() - 5 * 60000).toISOString(),
    updated_at: new Date(now.getTime() - 5 * 60000).toISOString(),
    items: [
      { id: 'oi-1', order_id: 'order-1', menu_item_id: 'item-1', menu_item_name: 'ข้าวผัดหมู', menu_item_category_id: 'cat-1', quantity: 1, unit_price: 50, total_price: 50, options: {}, notes: null, created_at: now.toISOString() },
      { id: 'oi-2', order_id: 'order-1', menu_item_id: 'item-3', menu_item_name: 'ข้าวไข่เจียว', menu_item_category_id: 'cat-1', quantity: 1, unit_price: 40, total_price: 40, options: {}, notes: null, created_at: now.toISOString() },
      { id: 'oi-3', order_id: 'order-1', menu_item_id: 'item-8', menu_item_name: 'น้ำมะนาว', menu_item_category_id: 'cat-3', quantity: 1, unit_price: 20, total_price: 15, options: {}, notes: null, created_at: now.toISOString() },
    ],
  },
  {
    id: 'order-2',
    order_number: 'ORD-002',
    line_user_id: 'other-user-456',
    customer_name: 'สมหญิง รักสวย',
    customer_phone: '082-222-2222',
    status: 'pending' as const,
    total_amount: 80,
    pickup_time: new Date(now.getTime() + 20 * 60000).toISOString(),
    notes: 'ไม่ใส่ผักชี',
    cancelled_reason: null,
    created_at: new Date(now.getTime() - 10 * 60000).toISOString(),
    updated_at: new Date(now.getTime() - 8 * 60000).toISOString(),
    items: [
      { id: 'oi-4', order_id: 'order-2', menu_item_id: 'item-2', menu_item_name: 'ข้าวกะเพราหมูสับ', menu_item_category_id: 'cat-1', quantity: 1, unit_price: 55, total_price: 55, options: {}, notes: null, created_at: now.toISOString() },
      { id: 'oi-5', order_id: 'order-2', menu_item_id: 'item-6', menu_item_name: 'ชาเย็น', menu_item_category_id: 'cat-3', quantity: 1, unit_price: 25, total_price: 25, options: {}, notes: null, created_at: now.toISOString() },
    ],
  },
  {
    id: 'order-3',
    order_number: 'ORD-003',
    line_user_id: 'other-user-789',
    customer_name: 'วิชัย มั่งมี',
    customer_phone: '083-333-3333',
    status: 'pending' as const,
    total_amount: 100,
    pickup_time: new Date(now.getTime() + 15 * 60000).toISOString(),
    notes: null,
    cancelled_reason: null,
    created_at: new Date(now.getTime() - 15 * 60000).toISOString(),
    updated_at: new Date(now.getTime() - 5 * 60000).toISOString(),
    items: [
      { id: 'oi-6', order_id: 'order-3', menu_item_id: 'item-5', menu_item_name: 'ต้มยำก๋วยเตี๋ยว', menu_item_category_id: 'cat-2', quantity: 1, unit_price: 55, total_price: 55, options: {}, notes: null, created_at: now.toISOString() },
      { id: 'oi-7', order_id: 'order-3', menu_item_id: 'item-4', menu_item_name: 'ก๋วยเตี๋ยวหมูน้ำใส', menu_item_category_id: 'cat-2', quantity: 1, unit_price: 45, total_price: 45, options: {}, notes: null, created_at: now.toISOString() },
    ],
  },
  {
    id: 'order-4',
    order_number: 'ORD-004',
    line_user_id: 'mock-user-123',
    customer_name: 'สมชาย ใจดี',
    customer_phone: '081-111-1111',
    status: 'ready' as const,
    total_amount: 70,
    pickup_time: new Date(now.getTime() + 5 * 60000).toISOString(),
    notes: null,
    cancelled_reason: null,
    created_at: new Date(now.getTime() - 25 * 60000).toISOString(),
    updated_at: new Date(now.getTime() - 2 * 60000).toISOString(),
    items: [
      { id: 'oi-8', order_id: 'order-4', menu_item_id: 'item-1', menu_item_name: 'ข้าวผัดหมู', menu_item_category_id: 'cat-1', quantity: 1, unit_price: 50, total_price: 50, options: {}, notes: null, created_at: now.toISOString() },
      { id: 'oi-9', order_id: 'order-4', menu_item_id: 'item-8', menu_item_name: 'น้ำมะนาว', menu_item_category_id: 'cat-3', quantity: 1, unit_price: 20, total_price: 20, options: {}, notes: null, created_at: now.toISOString() },
    ],
  },
];

export const mockAdmin = {
  id: 'admin-1',
  email: '111',
  name: 'Admin ทดสอบ',
  role: 'super_admin' as const,
  is_active: true,
  last_login: new Date().toISOString(),
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
};

export const mockLineProfile = {
  userId: 'mock-user-123',
  displayName: 'ผู้ใช้ทดสอบ',
  pictureUrl: undefined,
  statusMessage: 'Testing mode',
};
